{{- if .Values.deployRBAC }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  namespace: {{ template "namespace" . }}
  labels:
{{ include "labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  namespace: {{ template "namespace" . }}
  labels:
{{ include "labels" . | indent 4 }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}
  namespace: {{ template "namespace" . }}
  labels:
{{ include "labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}
  namespace: {{ template "namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
